apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: pdm
    secureJsonData:
      password: pdm
    jsonData:
      database: pdm
      sslmode: disable
      timescaledb: true
      postgresVersion: 1600
    isDefault: true
    editable: true
